version: "3"

services:
    bsc:
        build: ./bsc-node # Build local image
        container_name: bsc # Image name for docker cli access
        stop_signal: SIGINT
        stop_grace_period: 2m
        restart: unless-stopped # Restart policy
        volumes:
            - /home/orakuru/bsc:/bsc/node # Update /path/to/node
    
    orakuru:
        image: ghcr.io/orakurudata/crystal-ball:v0.2.1
        container_name: orakuru # Image name for docker cli access
        ports: 
            - 9000:9000 # Prometheus monitoring, comment if unused
        restart: on-failure:5 # Restart policy
        volumes:
            - /mnt/HC_Volume_11350147/orakuru:/orakuru/etc # Update /path/to/config
        environment:
            - CB_LOG_LEVEL=trace # Crystal Ball environment variables
        
        
